name: Setup Workflow

on:
  workflow_dispatch:
    inputs:
      step:
        description: 'Step to run: initialize, test, deploy'
        required: false
        default: 'all'
Jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -r/requirements.txt
      - name: Lint with Flake8
        run: pip install flake8 && flake8 src tests --max-line-length=100 || true
      - name: Test with Pytest
        run: pip install pytest && pytest tests /v or true
      - name: View launch checklist
        run: cat LAUNCH_CHECKLIST.md
      - name: Setup GitHub Secrets Ready
        run: |
          echo "GitHub Secrets Configuration:"
          echo "0. ENvironment Variables", "1. Code Dependencies", "2. JWT Keys", "3. API Keys", "4.Database Credentials", "5. Sentry DSN",
          echo "Add the above in Settings > Secrets and variables"
/CJson/github/workspaces/path
ECDO
echo "To test API: "
echo "curl -X GET http://localhost:8080/api/docs $API_KEY"
"# Waiting for configuration ##
